<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ __('add_new_tax') }}</title>

@extends('layouts.app')
@section('content')
<div class="page-body"><div class="container-fluid"><div class="row"><div class="col-12"><div class="card" style="margin-top:20px;"><div class="card-header pb-0 d-flex justify-content-between align-items-center"><h4 class="mb-0">{{ __('add_new_tax') }}</h4><a href="{{ route('taxes.manage') }}" class="btn btn-outline-secondary btn-sm"><i class="fa fa-arrow-left me-2"></i>{{ __('back_to_list') }}</a></div><div class="card-body"><form method="POST" action="{{ route('taxes.store') }}" class="theme-form">@csrf<div class="row g-4"><div class="col-lg-6"><label class="col-form-label">{{ __('tax_title') }} <span class="text-danger">*</span></label><input type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-6"><label class="col-form-label">{{ __('tax_amount') }} <span class="text-danger">*</span></label><input type="number" step="0.01" min="0" name="amount" class="form-control @error('amount') is-invalid @enderror" value="{{ old('amount') }}" required>@error('amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-6"><label class="col-form-label">{{ __('tax_type') }} <span class="text-danger">*</span></label><select name="calculation_type" class="form-select @error('calculation_type') is-invalid @enderror" required><option value="fixed" {{ old('calculation_type','fixed') == 'fixed' ? 'selected' : '' }}>{{ __('fixed_amount') }}</option><option value="percentage" {{ old('calculation_type') == 'percentage' ? 'selected' : '' }}>{{ __('percentage') }}</option></select>@error('calculation_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-6"><label class="col-form-label">{{ __('status') }} <span class="text-danger">*</span></label><select name="status" class="form-select @error('status') is-invalid @enderror" required><option value="1" {{ old('status','1') == '1' ? 'selected' : '' }}>{{ __('active') }}</option><option value="0" {{ old('status') == '0' ? 'selected' : '' }}>{{ __('inactive') }}</option></select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="text-end mt-4"><button type="submit" class="btn btn-primary px-5"><i class="fa fa-save me-2"></i>{{ __('save_tax') }}</button></div></form></div></div></div></div></div></div>
@endsection
